from .. import TransformFunction, string_to_tfarg_function, mime_type_based_transform, normalized_headers_to_tfarg_function


from encoded_script import encoded_script
from entity_encoding import entity_encoding_attributes_dec
from entity_encoding import entity_encoding_attributes_hex
from entity_encoding import entity_encoding_attributes_mix
from entity_encoding import entity_encoding_attributes_internal_entity
from entity_encoding import entity_encoding_attributes_internal_entities
from entity_encoding import entity_encoding_cdata_dec
from entity_encoding import entity_encoding_cdata_hex
from entity_encoding import entity_encoding_cdata_mix
from entity_encoding import entity_encoding_cdata_cdata
from entity_encoding import entity_encoding_cdata_internal_entity
from entity_encoding import entity_encoding_cdata_internal_entities
from entity_encoding import entity_encoding_root_internal_entity
from entity_encoding import entity_encoding_internal_entity_declaration_dec
from entity_encoding import entity_encoding_internal_entity_declaration_hex
from entity_encoding import entity_encoding_internal_entity_declaration_mix
from entity_encoding import entity_encoding_internal_parameter_entity_declaration_dec
from entity_encoding import entity_encoding_internal_parameter_entity_declaration_hex
from entity_encoding import entity_encoding_internal_parameter_entity_declaration_mix
from entity_encoding import entity_encoding_internal_entity_declaration_internal_parameter_entity
from entity_encoding import entity_encoding_internal_parameter_entity_declaration_nested_internal_parameter_entities
from insert_many_slash_after_html_opening_tag_name import insert_many_slash_after_html_opening_tag_name
from insert_many_slash_after_opening_tag_names import insert_many_slash_after_opening_tag_names
from insert_slash_after_opening_tag_names import insert_slash_after_opening_tag_names
from move_body_to_nested_div import move_body_to_nested_div
from move_body_to_nested_div_pad_children_in_last_one import move_body_to_nested_div_pad_children_in_last_one
from move_body_to_nested_div_with_children import move_body_to_nested_div_with_children
from null import null
from pad_body_with_div import pad_body_with_div
from remove_html_comments import remove_html_comments
from remove_content_type_http_equiv_meta import remove_content_type_http_equiv_meta

from xuacompatible import xua_move_meta_to_headers
from xuacompatible import xua_move_meta_to_xmlpi
from xuacompatible import xua_meta_change_value_8
from xuacompatible import xua_meta_change_value_9
from xuacompatible import xua_meta_change_value_10

from script_type_language import script_language_remove_encode
from script_type_language import script_language_add_encode

from declare_mime_type import meta_declared_text_html
from declare_mime_type import meta_declared_text_xml
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_no_type
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_no_type_inferred_xml
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_text_html
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_text_html_inferred_xml
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_text_xml
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_application_xml
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_application_xhtml_xml
from convert_to_xhtml import convert_to_xhtml_no_xml_tag_http_declared_image_svg_xml
from convert_to_xhtml import convert_to_xhtml_http_declared_no_type
from convert_to_xhtml import convert_to_xhtml_http_declared_no_type_inferred_html
from convert_to_xhtml import convert_to_xhtml_http_declared_text_html
from convert_to_xhtml import convert_to_xhtml_http_declared_text_html_inferred_html
from convert_to_xhtml import convert_to_xhtml_http_declared_text_xml
from convert_to_xhtml import convert_to_xhtml_http_declared_application_xml
from convert_to_xhtml import convert_to_xhtml_http_declared_application_xhtml_xml
from convert_to_xhtml import convert_to_xhtml_http_declared_image_svg_xml
from convert_to_xhtml import convert_to_xhtml_http_declared_image_gif
from convert_to_xhtml import convert_to_xhtml_http_declared_image_gif_inferred_html

from attributes import attributes_reverse
from attributes import attributes_insert_newlines
from attributes import attributes_insert_many_newlines

from external_resource import external_resource_internal_script


from data_url import data_url_internal_script_url_gen_nonstd_b64_declare_b64_encode_data_percent_encode_data_no
from data_url import data_url_internal_script_url_gen_nonstd_b64_declare_b64_encode_data_percent_encode_data
from data_url import data_url_internal_script_url_gen_nonstd_b64_declare_b64_encode_data_percent_encode_url
from data_url import data_url_internal_script_url_gen_std_b64_declare_b64_encode_data_percent_encode_data_no
from data_url import data_url_internal_script_url_gen_std_b64_declare_b64_encode_data_percent_encode_data
from data_url import data_url_internal_script_url_gen_std_b64_declare_b64_encode_data_percent_encode_url
from data_url import data_url_internal_script_url_gen_no_b64_declare_b64_encode_data_percent_encode_data_min
from data_url import data_url_internal_script_url_gen_no_b64_declare_b64_encode_data_percent_encode_data

from encodings import *
